module.exports = {
	SPIT: 'SPIT',
	SPITTED: 'SPITTED',
	GOT_SPITS: 'GOT_SPITS',

	GOT_CURRENT_USER : 'GOT_CURRENT_USER',
	GOT_USERS : 'GOT_USERS',

	FOLLOW: 'FOLLOW',
	FOLLOWED: 'FOLLOWED',

	UNFOLLOW: 'UNFOLLOW',
	UNFOLLOWED: 'UNFOLLOWED'

};
